FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="React Frontend for Library API"

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]