version: "3.3"

services: 
    library-api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        image: library_api_dev
        container_name: library_api
        restart: always
        volumes: 
            - /app/node_modules
            - ./server:/app
        # ports: 
        #     - 5000:5000
        depends_on: 
            - mongodb
        environment: 
            NODE_ENV: development
            MONGO_URI: mongodb://admin:password@mongodb
        networks: 
            - shared-network
    
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes: 
            - mongodb-data:/data/db
        networks: 
            - shared-network

    mongo-express:
        image: mongo-express
        container_name: mongo_express
        ports:
            - 8081:8081
        depends_on: 
            - mongodb
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
        networks: 
            - shared-network

    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        image: library_frontend_dev
        container_name: library_frontend
        restart: always
        volumes: 
            - /app/node_modules
            - ./client:/app
        # ports: 
        #     - 3000:3000
        depends_on: 
            - library-api
        networks: 
            - shared-network
    
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        restart: always
        ports: 
            - 8080:80
        depends_on: 
            - library-api
            - client
        networks: 
            - shared-network        

networks: 
    shared-network:
        driver: bridge

volumes: 
    mongodb-data:
        driver: local
        




            