FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="Development Image for MERN Library API"

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]